import Head from 'next/head';
import Banner from '../components/Banner';
import Footer from '../components/Footer';
import Header from '../components/Header';
import LargeCard from '../components/LargeCard';
import MediumCard from '../components/MediumCard';
import SmallCard from '../components/SmallCard';

export default function Home({ exploreData, cardData }) {
  return (
    <>
      <Head>
        <title>Airbnb clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* Header */}
        <Header />
        {/* Banner */}
        <Banner />

        <main className="max-w-7xl mx-auto px-8 sm:px-16">
          <section className="pt-6">
            <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

            {/* Pull some from a server - API endpoints */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {exploreData?.map(({ img, location, distance }) => (
                <SmallCard
                  key={img}
                  img={img}
                  distance={distance}
                  location={location}
                />
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>

            <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
              {cardData?.map(({ img, title }) => (
                <MediumCard key={img} img={img} title={title} />
              ))}
            </div>
          </section>

          <LargeCard
            img="https://links.papareact.com/4cj"
            title="The Greatest Outdoors"
            description="Whislists curated by Airbnb."
            buttonText="Get Inspired"
          />
        </main>

        <Footer />
      </div>
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G').then(
    (res) => res.json(),
  );

  const cardData = await fetch('https://www.jsonkeeper.com/b/VHHT').then(
    (res) => res.json(),
  );

  return {
    props: {
      exploreData,
      cardData,
    },
  };
}
